baseURL: https://lihua.ac.cn/
languageCode: en-us
title: Li Hua's blog
theme: "PaperMod"
params:
        # defaultTheme: light
        # defaultTheme: dark
        defaultTheme: auto
        homeInfoParams:
                Title: Hi there wave
                Content: Can be Info, links, about...
        profileMode:
                enabled: false
                title: "<Title>" # optional default will be site title
                subtitle: "This is subtitle"
                imageUrl: "<image link>" # optional
                # imageTitle: "<title of image as alt>" # optional
                imageWidth: 120 # custom size
                imageHeight: 120 # custom size
                buttons:
                        - name: Archive
                          url: "/archives"
                        - name: Github
                          url: "https://github.com/"
                # socialIcons: # optional
                #        - name: "<platform>"
                #          url: "<link>"
                #        - name: "<platform 2>"
                #          url: "<link2>"
        fuseOpts:
                isCaseSensitive: true
                shouldSort: true
                location: 0
                distance: 1000
                threshold: 0.4
                minMatchCharLength: 0
                keys: ["title", "permalink", "summary", "content"]
        ShowShareButtons: true
        ShowReadingTime: true
        ShowToc: true
        TocOpen: true
        ShowBreadCrumbs: true
        ShowPostNavLinks: true
        comments: true

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
